# Generated by Django 2.1.2 on 2019-04-17 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_idenity',
            new_name='user_identity',
        ),
    ]
